import logos from './logos'
import Vue from 'vue'

export default Vue.observable({
	logos,
	mini: false,
	ready: false,

	contacts: [
		{
			href: 'mailto:roblav96@gmail.com',
			icon: 'email',
			text: 'roblav96@gmail.com',
		},
		{
			href: 'tel:1-401-203-3195',
			icon: 'phone',
			text: '401-203-3195',
		},
		{
			href: 'https://goo.gl/maps/m7GoP5YY2bd9NL167',
			icon: 'map-marker',
			text: 'Boston, MA',
		},
	],

	socials: [
		{
			href: 'https://github.com/roblav96',
			icon: 'github',
			svg: logos.github[1],
			text: 'github/roblav96',
			subtext: 'roblav96',
		},
		{
			href: 'https://www.linkedin.com/in/roblav96/',
			icon: 'linkedin',
			svg: logos.linkedin[1],
			text: 'linkedin/roblav96',
			subtext: 'roblav96',
		},
	],

	traits: [
		['human-greeting', 'Altruistic, ego-free, humble, open-minded'],
		['account-tie', 'Leader, openly criticize, will take charge'],
		['teach', 'Eager to learn, more eager to teach'],
		['comment-quote-outline', '<i>"If you want to go far, go together"</i>'],
		['microphone-variant', 'Public seminar speaker & event attendee'],
		['counter', '+2,000 GitHub contributions yearly'],
	],

	technologies: [
		logos.typescript,
		logos.nodejs,
		logos.vuejs,
		logos.react,
		logos.rxjs,
		logos.redis,
		logos.mongodb,
		logos.googleanalytics,
		logos.aws,
		logos.apple,
		logos.android,
		logos.nativescript,
		logos.cordova,
		logos.ubuntu,
		logos.terminal,
		logos.sublimetext,
	],

	experiences: [
		{
			href: 'https://dochub.com/',
			logo: 'dochub.svg',
			company: 'DocHub',
			title: 'Lead Software Engineer',
			duration: 'May 2019 – Oct 2019',
			description: `Scaled product, integrated analytics, studied usage metrics, stripped out useless features`,
			technologies: [
				logos.emberjs,
				logos.coffeescript,
				logos.bootstrap,
				logos.sass,
				logos.webpack,
				logos.ruby,
				logos.rails,
				logos.googleanalytics,
				logos.nginx,
				logos.chef,
				logos.opsworks,
				logos.ec2,
				logos.iam,
				logos.rds,
			],
		},
		{
			href: 'https://github.com/roblav96/futon-media',
			logo: 'emby.png',
			company: 'Futon Media',
			title: 'Creator',
			duration: 'Sep 2018 – Dec 2019',
			description: `Instantly stream Movies and TV Shows via Emby Media`,
			technologies: [
				logos.react,
				logos.rxjs,
				logos.typescript,
				logos.nodejs,
				logos.redis,
				logos.csharp,
				logos.dotnet,
			],
		},
		{
			href: 'https://www.kava.io/',
			logo: 'kava.svg',
			company: 'Kava Labs',
			title: 'Senior Full-Stack Software Engineer',
			duration: 'Sep 2018 – Apr 2019',
			description: `Designed, developed, and deployed customer-facing 'Kava Switch' blockchain platform`,
			technologies: [
				logos.typescript,
				logos.nodejs,
				logos.vuejs,
				logos.vuetify,
				logos.sass,
				logos.webpack,
				logos.electron,
				logos.bitcoin,
				logos.ethereum,
				logos.redis,
				logos.ec2,
			],
		},
		{
			href: 'https://github.com/roblav96/robinhood.tools',
			logo: 'robinhood.svg',
			company: 'Robinhood Tools',
			title: 'Creator',
			duration: 'Dec 2016 – Aug 2018',
			description: `Advanced tools and resources for trading equities on Robinhood`,
			technologies: [
				logos.typescript,
				logos.nodejs,
				logos.vuejs,
				logos.bulma,
				logos.sass,
				logos.websocket,
				logos.redis,
				logos.nginx,
			],
		},
		{
			href: 'https://gethuman.com/',
			logo: 'gethuman.png',
			circle: true,
			company: 'GetHuman',
			title: 'Senior Full-Stack Software Engineer',
			duration: 'Sep 2016 – Aug 2017',
			description: `Designed, developed, and deployed native mobile platform on iOS & Android using NativeScript`,
			technologies: [
				logos.nativescript,
				logos.apple,
				logos.android,
				logos.amplitude,
				logos.typescript,
				logos.nodejs,
				logos.angular,
				logos.webpack,
				logos.stripe,
				logos.mongodb,
				logos.mocha,
			],
		},
		{
			href: 'https://mitrend.com/',
			logo: 'dell-emc.svg',
			company: 'EMC Corporation',
			title: 'Full-Stack Software Engineer',
			duration: 'Sep 2015 – Dec 2015',
			description: `Helped develop scanner reporting front-end in an agile environment using scrum methodologies`,
			technologies: [
				logos.nodejs,
				logos.mongodb,
				logos.mocha,
				logos.backbonejs,
				logos.marionettejs,
				logos.highcharts,
			],
		},
		{
			href: 'http://boustrisandsons.com/',
			logo: 'boustris.png',
			company: 'Boustris & Sons',
			title: 'Head of Information Technology',
			duration: 'Sep 2012 – Aug 2015',
			description: `Developed their fire alarm testing and inspection application & troubleshoot repair installed networked IT systems in commercial buildings`,
			technologies: [logos.cordova, logos.bootstrap, logos.jquery, logos.apache],
		},
		{
			href: 'https://facepunch.com/',
			logo: 'facepunch.svg',
			company: 'Facepunch Studios',
			title: 'Game Developer',
			duration: 'Jul 2007 – Aug 2009',
			description: `Developed games on Steam using the Lua programming language`,
			technologies: [logos.lua],
		},
	],

	educations: [
		{
			href:
				'https://drive.google.com/drive/folders/1n2ACUPYHlDKwC6tvhcjNTVTCDV1VAtxY?usp=sharing',
			logo: 'https://cdn.svgporn.com/logos/google-drive.svg',
			company: 'My Awesome PDFs',
			title: 'Personal collection of educational content',
			description: `Lean Analytics/Startup, Refactoring UI, Flavio Handbooks, Google Playbooks, Design Systems`,
		},
		{
			href: 'https://basecamp.com/books',
			logo: 'https://cdn.svgporn.com/logos/basecamp.svg',
			company: 'Books by Basecamp',
			title: 'Shape Up, Rework, Getting Real',
			description: `Shape Up: Stop Running in Circles and Ship Work that Matters | Rework: NYTimes bestseller about business | Getting Real: The smarter, faster, easier way to build a successful web application`,
		},
		{
			href: 'https://www.yourprimer.com/',
			logo: 'google-primer.png',
			company: 'Google Primer',
			title: 'Grow With Google Program',
			description: `Insights from trusted industry experts insights from trusted industry experts into jargon-free interactive lessons featuring practical next steps for reaching your business or career goals`,
		},
		{
			href: 'https://www.uri.edu/',
			logo: 'uri.svg',
			company: 'University of Rhode Island',
			title: 'Computer Science',
			duration: 'Sep 2009 – June 2010',
			description: `Voluntarily resigned due to financial constraints`,
		},
	],
})
