import logos from './logos'
import Vue from 'vue'

export default Vue.observable({
	logos,
	mini: false,
	ready: false,

	contacts: [
		{
			href: 'mailto:roblav96@gmail.com',
			icon: 'mdi-email',
			text: 'roblav96@gmail.com',
		},
		{
			href: 'tel:1-401-203-3195',
			icon: 'mdi-phone',
			text: '401-203-3195',
		},
		{
			href: 'https://goo.gl/maps/m7GoP5YY2bd9NL167',
			icon: 'mdi-map-marker',
			text: 'Boston, MA',
		},
	],

	socials: [
		{
			href: 'https://github.com/roblav96',
			icon: 'mdi-github-box',
			text: 'github/roblav96',
			subtext: 'roblav96',
		},
		{
			href: 'https://www.linkedin.com/in/roblav96/',
			icon: 'mdi-linkedin-box',
			text: 'linkedin/roblav96',
			subtext: 'roblav96',
		},
	],

	technologies: [
		logos.typescript,
		logos.nodejs,
		logos.vuejs,
		logos.redis,
		logos.mongodb,
		logos.aws,
		logos.nativescript,
		logos.apple,
		logos.android,
		logos.sublimetext,
		logos.terminal,
		logos.ubuntu,
		logos.github,
		logos.linkedin,
		logos.pdf,
	],

	experiences: [
		{
			logo: 'dochub.svg',
			title: 'Lead Product Engineer',
			company: 'DocHub',
			href: 'https://dochub.com/',
			duration: 'May 2019 – Oct 2019',
			description: `Scaled product, integrated analytics, studied usage metrics, stripped out useless features`,
			technologies: [
				logos.emberjs,
				logos.coffeescript,
				logos.bootstrap,
				logos.ruby,
				logos.rails,
				logos.googleanalytics,
				logos.nginx,
				logos.chef,
				logos.opsworks,
				logos.ec2,
				logos.iam,
				logos.rds,
			],
		},
		{
			logo: 'emby.png',
			title: 'Creator',
			company: 'Futon Media',
			href: 'https://github.com/roblav96/futon-media',
			duration: 'Sep 2018 – Dec 2019',
			description: `Instantly stream Movies and TV Shows via Emby Media`,
			technologies: [logos.typescript, logos.nodejs, logos.redis, logos.dotnet, logos.csharp],
		},
		{
			logo: 'kava.svg',
			title: 'Senior Full-Stack Software Engineer',
			company: 'Kava Labs',
			href: 'https://www.kava.io/',
			duration: 'Sep 2018 – Apr 2019',
			description: `Designed, developed, and deployed customer-facing 'Kava Switch' blockchain platform`,
			technologies: [
				logos.typescript,
				logos.vuejs,
				logos.vuetify,
				logos.sass,
				logos.webpack,
				logos.electron,
				logos.nodejs,
				logos.bitcoin,
				logos.ethereum,
				logos.redis,
				logos.ec2,
			],
		},
		{
			logo: 'robinhood.svg',
			title: 'Creator',
			company: 'Robinhood Tools',
			href: 'https://github.com/roblav96/robinhood.tools',
			duration: 'Dec 2016 – Aug 2018',
			description: `Advanced trading tools and resources for Robinhood`,
			technologies: [
				logos.vuejs,
				logos.bulma,
				logos.sass,
				logos.typescript,
				logos.nodejs,
				logos.websocket,
				logos.redis,
				logos.nginx,
			],
		},
		{
			logo: 'gethuman.png',
			title: 'Senior Full-Stack Software Engineer',
			company: 'GetHuman',
			href: 'https://gethuman.com/',
			duration: 'Sep 2016 – Aug 2017',
			description: `Designed, developed, and deployed native mobile platform on iOS & Android using NativeScript`,
			technologies: [
				logos.nativescript,
				logos.apple,
				logos.android,
				logos.amplitude,
				logos.angular,
				logos.typescript,
				logos.webpack,
				logos.stripe,
				logos.mocha,
				logos.mongodb,
			],
		},
		{
			logo: 'dell-emc.svg',
			title: 'Full-Stack Software Engineer',
			company: 'EMC Corporation',
			href: 'https://mitrend.com/',
			duration: 'Sep 2015 – Dec 2015',
			description: `Helped develop scanner reporting front-end in an agile environment using scrum methodologies`,
			technologies: [
				logos.backbonejs,
				logos.marionettejs,
				logos.highcharts,
				logos.nodejs,
				logos.mongodb,
				logos.mocha,
			],
		},
		{
			logo: 'boustris.png',
			title: 'Head of Information Technology',
			company: 'Boustris & Sons',
			href: 'http://boustrisandsons.com/',
			duration: 'Sep 2012 – Aug 2015',
			description: `Developed their fire alarm testing and inspection application & troubleshoot repair installed networked IT systems in commercial buildings`,
			technologies: [logos.bootstrap, logos.jquery, logos.apache],
		},
		{
			logo: 'facepunch.svg',
			title: 'Game Developer',
			company: 'Facepunch Studios',
			href: 'https://facepunch.com/',
			duration: 'Jul 2007 – Aug 2009',
			description: `Developed games on Steam using the Lua programming language`,
			technologies: [logos.lua],
		},
	],
})
